addiction:
  use_threshold: 5
  withdrawal_time: 3600
  withdrawal_effects:
    - "WEAKNESS:1:600"
    - "SLOWNESS:1:600"
hologram:
  update_interval: 5
  format: "&aGrowth: &e%percentage%%"
gui:
  main_menu_title: "&5DrugCraft Menu"
  buy_menu_title: "&2Buy Drugs"
  sell_menu_title: "&eSell Drugs"
  give_menu_title: "&cGive Drugs"
npc:
  sell_message: "&aSold %drug% for $%price%!"