name: DrugCraft
version: 1.0.0
main: com.spence.drugcraft.DrugCraft
api-version: 1.21
depend: [Citizens, DecentHolograms, Essentials, NBTAPI, LuckPerms, Vault]
commands:
  drugadmin:
    description: Admin commands for DrugCraft
    usage: /<command> [clearcrops]
    permission: drugcraft.admin
  cartel:
    description: Manage drug cartels
    usage: /<command> <create|invite|join|leave|info> [args]
    permission: drugcraft.cartel
permissions:
  drugcraft.admin:
    description: Allows access to DrugCraft admin commands
    default: op
  drugcraft.use:
    description: Allows interaction with DrugCraft NPCs
    default: true
  drugcraft.cartel:
    description: Allows use of cartel commands
    default: true
  drugcraft.bypass.police:
    description: Bypasses police detection
    default: op