name: DrugCraft
version: 1.0-SNAPSHOT
main: com.spence.drugcraft.DrugCraft
api-version: 1.21
depend: [Vault]
commands:
  drug:
    description: Manage drugs in DrugCraft
    usage: /<command> <gui|give|sell|info|reset>
permissions:
  drugcraft.admin:
    description: Allows access to admin features
    default: op
  drugcraft.give:
    description: Allows giving drugs
    default: op
description: A fictional drug-themed plugin for Minecraft. Does not promote real-world drug use.