name: DrugCraft
version: 1.0.0
main: com.spence.drugcraft.DrugCraft
api-version: 1.21
depend: [Vault, Citizens, WorldGuard, WorldEdit, LuckPerms, Essentials, EssentialsChat, DecentHolograms, NBTAPI]
commands:
  business:
    description: Opens the business GUI
    usage: /<command>
  cartel:
    description: Opens the cartel GUI
    usage: /<command>
  casino:
    description: Opens the casino GUI
    usage: /<command>
  games:
    description: Opens the games GUI
    usage: /<command>
  heists:
    description: Opens the heists GUI
    usage: /<command>
  player:
    description: Opens the player GUI
    usage: /<command>
  admin:
    description: Opens the admin GUI
    usage: /<command>