name: DrugCraft
version: 1.0.0
main: com.spence.drugcraft.DrugCraft
api-version: 1.21
depend: [item-nbt-api, DecentHolograms, Vault, Citizens, PlaceholderAPI]
softdepend: [LuckPerms, ProtocolLib, EssentialsX]
description: A plugin to manage drugs and crops with custom effects, NPC selling, and addiction system.
authors: [YoImSpence]
website: https://github.com/YoImSpence/DrugCraft

commands:
  drug:
    description: Opens the DrugCraft GUI or manages drugs.
    usage: /<command> [buy|sell|give]
    permission: drugcraft.use

permissions:
  drugcraft.use:
    description: Allows players to use the /drug command.
    default: true
  drugcraft.admin:
    description: Allows admins to give drugs.
    default: op